import { defineStore } from 'pinia'

export const useComputerStore = defineStore('computerStore', {
  state: () => ({
    computers: [
      {
        id: 1,
        user_name: 'Achara',
        office_name: 'NRA',
        asset_tag: 'CO-20-03-151-OHO109',
        serial: 'CND9416P3B',
        brand: 'HP Laptop 15-db1048AU',
      },
      {
        id: 2,
        user_name: 'Arpatcha',
        office_name: 'NRA',
        asset_tag: 'CO-19-07-134-OHO96',
        serial: '5CG91413QL',
        brand: 'HP Laptop 14s-cf1016TX',
      },
      {
        id: 3,
        user_name: 'Danuya',
        office_name: 'NPM',
        asset_tag: 'CO-22-02-26',
        serial: 'PF3ATJSN',
        brand: 'LENOVO IdeaPad 3 14ITL05',
      },
      {
        id: 4,
        user_name: 'Napasorn',
        office_name: 'NPM',
        asset_tag: 'CO-19-06-131-OHO93',
        serial: '8CG8481HMX',
        brand: 'HP Envy x360',
      },
      {
        id: 5,
        user_name: 'Ketwadee',
        office_name: 'NPC',
        asset_tag: 'NPC-CO-22-08-001',
        serial: 'DQBG7ST00621300E783000',
        brand: 'Acer All-in-One Aspire C22-1650',
      },
      {
        id: 6,
        user_name: 'Massupa',
        office_name: 'NPC',
        asset_tag: 'CO-20-03-149-OHO107',
        serial: 'DQBD9ST00400106C103000',
        brand: 'Acer Aspire All-in-One C22-960',
      },
      {
        id: 7,
        user_name: 'Patcharaporn Pankaew',
        office_name: 'NRT',
        asset_tag: 'CO-23-04-001_NRT',
        serial: '5CD238LTML',
        brand: 'HP 15s-fq5156TU',
      },
      {
        id: 8,
        user_name: 'Pichan Suwanasiri',
        office_name: 'NPA',
        asset_tag: 'CO-16-11-101',
        serial: 'CND6255WKZ',
        brand: 'HP Notbook-15-ac674tx',
      },
      {
        id: 9,
        user_name: 'Phakwarin Siraamrawong',
        office_name: 'NPA',
        asset_tag: 'CO-20-03-151-demo9',
        serial: 'CND9416P3B',
        brand: 'HP Laptop demo9',
      },
      {
        id: 10,
        user_name: 'Anucha',
        office_name: 'OHO',
        asset_tag: 'OHO-23-01-160 OHO',
        serial: 'N7N0LP02K719299',
        brand: 'ASUS X1402ZA-EB501WS',
      },
    ],
    printers: [],
    others: [],
  }),
})
