import { defineStore } from 'pinia'

export const useAssetsStore = defineStore('assetsStore', {
  state: () => ({
    assets: [
      // COMPUTER MOCKUP DATA
      {
        id: 1,
        catalog: 'computer',
        user_name: 'Achara',
        office_name: 'NRA',
        asset_tag: 'CO-20-03-151-OHO109',
        serial: 'CND9416P3B',
        brand: 'HP Laptop 15-db1048AU',
      },
      {
        id: 2,
        catalog: 'computer',
        user_name: 'Arpatcha',
        office_name: 'NRA',
        asset_tag: 'CO-19-07-134-OHO96',
        serial: '5CG91413QL',
        brand: 'HP Laptop 14s-cf1016TX',
      },
      {
        id: 3,
        catalog: 'computer',
        user_name: 'Danuya',
        office_name: 'NPM',
        asset_tag: 'CO-22-02-26',
        serial: 'PF3ATJSN',
        brand: 'LENOVO IdeaPad 3 14ITL05',
      },
      {
        id: 4,
        catalog: 'computer',
        user_name: 'Napasorn',
        office_name: 'NPM',
        asset_tag: 'CO-19-06-131-OHO93',
        serial: '8CG8481HMX',
        brand: 'HP Envy x360',
      },
      {
        id: 5,
        catalog: 'computer',
        user_name: 'Ketwadee',
        office_name: 'NPC',
        asset_tag: 'NPC-CO-22-08-001',
        serial: 'DQBG7ST00621300E783000',
        brand: 'Acer All-in-One Aspire C22-1650',
      },
      {
        id: 6,
        catalog: 'computer',
        user_name: 'Massupa',
        office_name: 'NPC',
        asset_tag: 'CO-20-03-149-OHO107',
        serial: 'DQBD9ST00400106C103000',
        brand: 'Acer Aspire All-in-One C22-960',
      },
      {
        id: 7,
        catalog: 'computer',
        user_name: 'Patcharaporn Pankaew',
        office_name: 'NRT',
        asset_tag: 'CO-23-04-001_NRT',
        serial: '5CD238LTML',
        brand: 'HP 15s-fq5156TU',
      },
      {
        id: 8,
        catalog: 'computer',
        user_name: 'Pichan Suwanasiri',
        office_name: 'NPA',
        asset_tag: 'CO-16-11-101',
        serial: 'CND6255WKZ',
        brand: 'HP Notbook-15-ac674tx',
      },
      {
        id: 9,
        catalog: 'computer',
        user_name: 'Phakwarin Siraamrawong',
        office_name: 'NPA',
        asset_tag: 'CO-20-03-151-demo9',
        serial: 'CND9416P3B',
        brand: 'HP Laptop demo9',
      },
      {
        id: 10,
        catalog: 'computer',
        user_name: 'Anucha',
        office_name: 'OHO',
        asset_tag: 'OHO-23-01-160 OHO',
        serial: 'N7N0LP02K719299',
        brand: 'ASUS X1402ZA-EB501WS',
      },
      // PRINTER MOCKUP DATA
      {
        id: 11,
        catalog: 'printer',
        user_name: 'Achara',
        office_name: 'NRA',
        asset_tag: 'CO-20-03-151-OHO109',
        serial: 'CND9416P3B',
        brand: 'HP Smart Tank 520',
      },
      {
        id: 12,
        user_name: 'Arpatcha',
        catalog: 'printer',
        office_name: 'NRA',
        asset_tag: 'CO-19-07-134-OHO96',
        serial: '5CG91413QL',
        brand: 'HP Smart Tank 670',
      },
      {
        id: 13,
        catalog: 'printer',
        user_name: 'Danuya',
        office_name: 'NPM',
        asset_tag: 'CO-22-02-26',
        serial: 'PF3ATJSN',
        brand: 'CANNON PIXMA E410',
      },
      {
        id: 14,
        catalog: 'printer',
        user_name: 'Napasorn',
        office_name: 'NPM',
        asset_tag: 'CO-19-06-131-OHO93',
        serial: '8CG8481HMX',
        brand: 'CANNON PIXMA E4570',
      },
      {
        id: 15,
        catalog: 'printer',
        user_name: 'Ketwadee',
        office_name: 'NPC',
        asset_tag: 'NPC-CO-22-08-001',
        serial: 'DQBG7ST00621300E783000',
        brand: 'CANNON PIXMA E4570',
      },
      {
        id: 16,
        catalog: 'printer',
        user_name: 'Massupa',
        office_name: 'NPC',
        asset_tag: 'CO-20-03-149-OHO107',
        serial: 'DQBD9ST00400106C103000',
        brand: 'BROTHER DCP-T320',
      },
      {
        id: 17,
        catalog: 'printer',
        user_name: 'Patcharaporn Pankaew',
        office_name: 'NRT',
        asset_tag: 'CO-23-04-001_NRT',
        serial: '5CD238LTML',
        brand: 'CANNON PIXMA E4570',
      },
      {
        id: 18,
        catalog: 'printer',
        user_name: 'Pichan Suwanasiri',
        office_name: 'NPA',
        asset_tag: 'CO-16-11-101',
        serial: 'CND6255WKZ',
        brand: 'BROTHER DCP-T430',
      },
      {
        id: 19,
        catalog: 'printer',
        user_name: 'Phakwarin Siraamrawong',
        office_name: 'NPA',
        asset_tag: 'CO-20-03-151-demo9',
        serial: 'CND9416P3B',
        brand: 'BROTHER DCP-T430',
      },
      {
        id: 20,
        catalog: 'printer',
        user_name: 'Anucha',
        office_name: 'OHO',
        asset_tag: 'OHO-23-01-160 OHO',
        serial: 'N7N0LP02K719299',
        brand: 'EPSON L3210',
      },
      // SOFTWARE MOCKUP DATA
      {
        id: 20,
        catalog: 'software',
        expire_date: '25-11-01',
        user_name: 'Kanjana',
        office_name: 'CONSPIRE',
        asset_tag: 'CO-23-01-2',
        serial: 'Adobe-demo-serial20',
        brand: 'Adobe Create suite',
      },
      {
        id: 21,
        catalog: 'software',
        expire_date: '25-11-01',
        user_name: '',
        office_name: 'NPC',
        asset_tag: '',
        serial: 'MS-demo-serial21',
        brand: 'Exchange Email',
      },
      {
        id: 22,
        catalog: 'software',
        expire_date: '25-11-01',
        user_name: '',
        office_name: 'NRA',
        asset_tag: '',
        serial: 'Adobe-demo-serial22',
        brand: 'Adobe Acrobat Pro',
      },
      {
        id: 23,
        catalog: 'software',
        expire_date: '25-11-01',
        user_name: '',
        office_name: 'NRA',
        asset_tag: '',
        serial: 'N7N0LP02K719299',
        brand: 'AutoCAD Lite',
      },
    ],
  }),
  actions: {
    addAsset(newAsset) {
      // assets is object
      this.assets.push(newAsset)
    },
    deleteAsset(assetId) {
      this.assets = this.assets.filter((asset) => {
        return asset.id !== assetId
      })
    },
  },
})
