export const mockStaff = [
  {
    id: 1,
    fname: 'Sumita',
    lname: 'Khongnok',
    email: 'sumita@nexus.co.th',
    department: 'Finance & Accounting',
    office_id: '2',
  },
  {
    id: 2,
    fname: 'Nattapon',
    lname: 'Muangnanta',
    email: 'nattapon@nexus.co.th',
    department: 'Valuation Advisory',
    office_id: '2',
  },
  {
    id: 3,
    fname: 'Napasorn',
    lname: 'Makchuay',
    email: 'napasorn@nexus.co.th',
    department: 'Marketing Communication',
    office_id: '3',
  },
  {
    id: 4,
    fname: 'Chavanut',
    lname: 'Jangprasitchai',
    email: 'chavanut@nexus.co.th',
    department: 'Land Acquistion',
    office_id: '1',
  },
  {
    id: 5,
    fname: 'Meeting Room',
    lname: '',
    email: '',
    department: 'Central Administrations',
    office_id: '2',
  },
  {
    id: 6,
    fname: 'Patthama',
    lname: 'Sinprasertporn',
    email: 'patthama@nexus.co.th',
    department: 'Sales Services',
    office_id: '3',
  },
  {
    id: 7,
    fname: 'Arpatcha',
    lname: 'Tonpoo',
    email: 'apatcha@nexus.co.th,Investment Advisory',
    office_id: '4',
  },
  {
    id: 8,
    fname: 'Patcharin',
    lname: 'Kotama',
    email: 'patcharin@nexus.co.th',
    department: 'Central Administrations',
    office_id: '2',
  },
  {
    id: 9,
    fname: 'Natthida',
    lname: 'Mairieng',
    email: 'natthida@nexus.co.th',
    department: 'Business Development',
    office_id: '3',
  },
  {
    id: 10,
    fname: 'Seksan',
    lname: 'Hiranprasatkul',
    email: 'seksan@nexus.co.th',
    department: 'Valuation Advisory',
    office_id: '2',
  },
  {
    id: 11,
    fname: 'Massupa',
    lname: 'Seangthong',
    email: 'massupa@nexus.co.th',
    department: 'Finance & Accounting',
    office_id: '2',
  },
  {
    id: 12,
    fname: 'Ayika',
    lname: 'Suntornkrut',
    email: 'ayika@nexus.co.th',
    department: 'Valuation Advisory',
    office_id: '2',
  },
  {
    id: 13,
    fname: 'Achara',
    lname: 'Mahaolan',
    email: 'achara@nexus.co.th',
    department: 'Valuation Advisory',
    office_id: '2',
  },
  {
    id: 14,
    fname: 'Satita',
    lname: 'Teepatimakorn',
    email: 'satita@nexus.co.th',
    department: 'Investment Advisory',
    office_id: '4',
  },
  {
    id: 15,
    fname: 'Karnjana',
    lname: 'Chaisirikul',
    email: '',
    department: 'Conspire',
    office_id: '7',
  },
  {
    id: 16,
    fname: 'Danuya',
    lname: 'Taechamongkalapiwat',
    email: 'danuya@nexus.co.th',
    department: 'Marketing Communication',
    office_id: '3',
  },
  {
    id: 17,
    fname: 'Ketwadee',
    lname: 'Dangbunjong',
    email: 'ketwadee@nexus.co.th',
    department: 'Central Administrations',
    office_id: '2',
  },
  {
    id: 18,
    fname: 'Patcharaporn',
    lname: 'Pankaew',
    email: 'patcharaporn@nexus.co.th',
    department: 'Retail  Services',
    office_id: '5',
  },
  {
    id: 19,
    fname: 'Atipa',
    lname: 'Muthita',
    email: 'atipa@nexus.co.th',
    department: 'Research Advisory',
    office_id: '4',
  },
  {
    id: 20,
    fname: 'Teerawit',
    lname: 'Limthongsakul',
    email: 'teerawit@nexus.co.th',
    department: '',
    office_id: '4',
  },
  {
    id: 21,
    fname: 'Nalinrat',
    lname: 'Chareonsuphong',
    email: 'nalinrat@nexus.co.th',
    department: ',3',
  },
  {
    id: 22,
    fname: 'Noppakrit',
    lname: 'Phuwasiriwarakit',
    email: 'noppakrit@nexus.co.th',
    department: 'Land Acquistion',
    office_id: '1',
  },
  {
    id: 23,
    fname: 'Thanawat',
    lname: 'Charoenthirasakundet',
    email: 'thanawat@nexus.co.th',
    department: 'Research Advisory',
    office_id: '4',
  },
  {
    id: 24,
    fname: 'Saravadee',
    lname: 'Vanichsombat',
    email: 'saravadee@nexus.co.th',
    department: '',
    office_id: '1',
  },
  {
    id: 25,
    fname: 'Anucha',
    lname: 'Kasun',
    email: 'anucha@oho.co.th',
    department: 'OHO service',
    office_id: '6',
  },
  {
    id: 26,
    fname: 'Sirapop',
    lname: 'Chutsittidate',
    email: 'sipapop@nexus.co.th',
    department: 'Sales Service',
    office_id: '3',
  },
]
